name: card_scanner
description: Fast, Accurate and Secure Credit & Debit card scanning library for flutter.
version: 1.0.2
homepage: https://github.com/nateshmbhat/card-scanner-flutter
repository: https://github.com/nateshmbhat/card-scanner-flutter

environment:
  sdk: ^3.9.2
  flutter: ">=3.3.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  plugin:
    platforms:
      android:
        package: com.nateshmbhat.card_scanner
        pluginClass: CardScannerPlugin
      ios:
        pluginClass: CardScannerPlugin
